// Generated code - do not modify

// These modules will be generated by the build.rs script
// Uncomment these when the code generation is working
// pub mod registry;
// pub mod resolver;
// pub mod reverse_registrar;

// Placeholder implementations until code generation is working
pub mod registry {
    pub mod events {
        pub struct NewOwner;
        pub struct Transfer;
        pub struct NewResolver;
    }
    
    pub mod functions {
        pub struct Resolver;
    }
}

pub mod resolver {
    pub mod events {
        pub struct AddrChanged;
        pub struct NameChanged;
    }
    
    pub mod functions {
        pub struct Addr;
        pub struct Name;
    }
}

pub mod reverse_registrar {
    pub mod events {
        pub struct ReverseClaimed;
    }
    
    pub mod functions {
        pub struct Node;
    }
}
