// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    /// <https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/IERC20Metadata.sol>
    #[prost(message, repeated, tag="1")]
    pub metadata_by_contracts: ::prost::alloc::vec::Vec<MetadataByContract>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetadataByContract {
    /// log.address
    #[prost(bytes="vec", tag="1")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
    /// decimals() -> uint8 (REQUIRED)
    #[prost(int32, tag="2")]
    pub decimals: i32,
    /// symbol() -> string
    #[prost(string, optional, tag="3")]
    pub symbol: ::core::option::Option<::prost::alloc::string::String>,
    /// name() -> string
    #[prost(string, optional, tag="4")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
}
// @@protoc_insertion_point(module)
