// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub allowance_storage_changes: ::prost::alloc::vec::Vec<AllowanceStorageChange>,
    /// -- debug --
    #[prost(message, repeated, tag="2")]
    pub approvals_events: ::prost::alloc::vec::Vec<ApprovalEvent>,
    #[prost(message, repeated, tag="3")]
    pub transfer_from_functions: ::prost::alloc::vec::Vec<TransferFromFunction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AllowanceStorageChange {
    /// -- transaction --
    #[prost(bytes="vec", tag="5")]
    pub transaction_id: ::prost::alloc::vec::Vec<u8>,
    /// -- allowance --
    ///
    /// log.address
    #[prost(bytes="vec", tag="20")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="21")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="22")]
    pub spender: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="23")]
    pub value: ::prost::alloc::string::String,
    /// -- debug --
    #[prost(enumeration="Algorithm", tag="100")]
    pub algorithm: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApprovalEvent {
    /// -- transaction --
    #[prost(bytes="vec", tag="5")]
    pub transaction_id: ::prost::alloc::vec::Vec<u8>,
    /// -- call --
    ///
    /// call.caller
    #[prost(bytes="vec", tag="8")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    /// -- ordering --
    ///
    /// log.ordinal
    #[prost(uint64, tag="10")]
    pub ordinal: u64,
    /// -- approval --
    ///
    /// log.address
    #[prost(bytes="vec", tag="20")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="21")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="22")]
    pub spender: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="23")]
    pub value: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferFromFunction {
    /// -- transaction --
    #[prost(bytes="vec", tag="5")]
    pub transaction_id: ::prost::alloc::vec::Vec<u8>,
    /// -- call --
    #[prost(bytes="vec", tag="8")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="10")]
    pub begin_ordinal: u64,
    #[prost(uint64, tag="11")]
    pub end_ordinal: u64,
    #[prost(uint32, tag="12")]
    pub index: u32,
    /// -- transfer from --
    ///
    /// log.address
    #[prost(bytes="vec", tag="20")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="21")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="22")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="23")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Algorithm {
    Unspecified = 0,
    /// approval event
    Approval = 1,
    /// transfer_from event
    TransferFrom = 2,
    /// permit event
    Permit = 3,
}
impl Algorithm {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Algorithm::Unspecified => "ALGORITHM_UNSPECIFIED",
            Algorithm::Approval => "ALGORITHM_APPROVAL",
            Algorithm::TransferFrom => "ALGORITHM_TRANSFER_FROM",
            Algorithm::Permit => "ALGORITHM_PERMIT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ALGORITHM_UNSPECIFIED" => Some(Self::Unspecified),
            "ALGORITHM_APPROVAL" => Some(Self::Approval),
            "ALGORITHM_TRANSFER_FROM" => Some(Self::TransferFrom),
            "ALGORITHM_PERMIT" => Some(Self::Permit),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
